In [82]:
# %load_ext autoreload
# %autoreload 2
# %matplotlib inline


import pandas as pd
import numpy as np
# from fastai.imports import *
# from fastai.structured import *

from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

In [115]:
data = pd.read_csv('Train.csv')
# pd.options.display.max_columns = None  #added to show all the columns inplace of the dots.
data.head(10)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3018: DtypeWarning: Columns (13,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


SalesID  SalePrice  MachineID  ModelID  datasource  auctioneerID  YearMade  \
0  1139246      66000     999089     3157         121           3.0      2004   
1  1139248      57000     117657       77         121           3.0      1996   
2  1139249      10000     434808     7009         121           3.0      2001   
3  1139251      38500    1026470      332         121           3.0      2001   
4  1139253      11000    1057373    17311         121           3.0      2007   
5  1139255      26500    1001274     4605         121           3.0      2004   
6  1139256      21000     772701     1937         121           3.0      1993   
7  1139261      27000     902002     3539         121           3.0      2001   
8  1139272      21500    1036251    36003         121           3.0      2008   
9  1139275      65000    1016474     3883         121           3.0      1000   

   MachineHoursCurrentMeter UsageBand         saledate        ...         \
0                      68.0       Low  11/16/2006 0:00        ...          
1                    4640.0       Low   3/26/2004 0:00        ...          
2                    2838.0      High   2/26/2004 0:00        ...          
3                    3486.0      High   5/19/2011 0:00        ...          
4                     722.0    Medium   7/23/2009 0:00        ...          
5                     508.0       Low  12/18/2008 0:00        ...          
6                   11540.0      High   8/26/2004 0:00        ...          
7                    4883.0      High  11/17/2005 0:00        ...          
8                     302.0       Low   8/27/2009 0:00        ...          
9                   20700.0    Medium    8/9/2007 0:00        ...          

  Undercarriage_Pad_Width         Stick_Length                Thumb  \
0                     NaN                  NaN                  NaN   
1                     NaN                  NaN                  NaN   
2                     NaN                  NaN                  NaN   
3                     NaN                  NaN                  NaN   
4                     NaN                  NaN                  NaN   
5                     NaN                  NaN                  NaN   
6     None or Unspecified  None or Unspecified  None or Unspecified   
7                     NaN                  NaN                  NaN   
8     None or Unspecified  None or Unspecified  None or Unspecified   
9                     NaN                  NaN                  NaN   

       Pattern_Changer Grouser_Type Backhoe_Mounting Blade_Type  \
0                  NaN          NaN              NaN        NaN   
1                  NaN          NaN              NaN        NaN   
2                  NaN          NaN              NaN        NaN   
3                  NaN          NaN              NaN        NaN   
4                  NaN          NaN              NaN        NaN   
5                  NaN          NaN              NaN        NaN   
6  None or Unspecified       Double              NaN        NaN   
7                  NaN          NaN              NaN        NaN   
8  None or Unspecified       Double              NaN        NaN   
9                  NaN          NaN              NaN        NaN   

  Travel_Controls Differential_Type Steering_Controls  
0             NaN          Standard      Conventional  
1             NaN          Standard      Conventional  
2             NaN               NaN               NaN  
3             NaN               NaN               NaN  
4             NaN               NaN               NaN  
5             NaN               NaN               NaN  
6             NaN               NaN               NaN  
7             NaN               NaN               NaN  
8             NaN               NaN               NaN  
9             NaN          Standard      Conventional  

[10 rows x 53 columns]

In [114]:
val  = pd.get_dummies(data.Thumb) #One hot encoding to remove categorial data when you have less variation in the feature.
val
# data.SalePrice = np.log(data.SalePrice)

Hydraulic  Manual  None or Unspecified
0               0       0                    0
1               0       0                    0
2               0       0                    0
3               0       0                    0
4               0       0                    0
5               0       0                    0
6               0       0                    1
7               0       0                    0
8               0       0                    1
9               0       0                    0
10              0       0                    0
11              0       0                    0
12              0       0                    1
13              0       0                    0
14              0       0                    0
15              0       0                    0
16              0       0                    1
17              0       0                    1
18              0       0                    1
19              0       0                    0
20              0       0                    1
21              0       0                    0
22              0       0                    1
23              0       0                    0
24              0       0                    0
25              0       0                    0
26              0       0                    1
27              0       0                    1
28              0       0                    0
29              0       0                    1
...           ...     ...                  ...
401095          0       0                    1
401096          0       0                    1
401097          0       0                    1
401098          0       0                    1
401099          0       0                    1
401100          0       0                    1
401101          0       0                    1
401102          0       0                    1
401103          0       0                    1
401104          0       0                    1
401105          0       0                    1
401106          0       0                    1
401107          0       0                    1
401108          0       0                    1
401109          0       0                    1
401110          0       0                    1
401111          0       0                    1
401112          0       0                    1
401113          0       0                    1
401114          0       0                    1
401115          0       0                    1
401116          0       0                    1
401117          0       0                    1
401118          0       0                    1
401119          0       0                    1
401120          0       0                    1
401121          0       0                    1
401122          0       0                    1
401123          0       0                    1
401124          0       0                    1

[401125 rows x 3 columns]

In [4]:
data.SalePrice

0         11.097410
1         10.950807
2          9.210340
3         10.558414
4          9.305651
5         10.184900
6          9.952278
7         10.203592
8          9.975808
9         11.082143
10        10.085809
11        10.021271
12        10.491274
13        10.325482
14        10.239960
15         9.852194
16         9.510445
17         9.159047
18         9.433484
19         9.350102
20        10.621327
21        10.448715
22        10.165852
23        11.198215
24        10.404263
25         9.433484
26         9.648595
27        10.878047
28        10.736397
29        11.396392
            ...    
401095     9.259131
401096     9.210340
401097     9.047821
401098     9.259131
401099     9.305651
401100     9.259131
401101     9.210340
401102     9.259131
401103     9.433484
401104     9.259131
401105     9.210340
401106     9.259131
401107     9.433484
401108     9.259131
401109     9.259131
401110     9.259131
401111     9.210340
401112     9.259131
401113     9.259131


In [4]:
# ?RandomForestRegressor  #to see the documentation
# ??RandomForestRegressor  #to see the code behind the object.
data.columns

Index(['SalesID', 'SalePrice', 'MachineID', 'ModelID', 'datasource',
       'auctioneerID', 'YearMade', 'MachineHoursCurrentMeter', 'UsageBand',
       'saledate', 'fiModelDesc', 'fiBaseModel', 'fiSecondaryDesc',
       'fiModelSeries', 'fiModelDescriptor', 'ProductSize',
       'fiProductClassDesc', 'state', 'ProductGroup', 'ProductGroupDesc',
       'Drive_System', 'Enclosure', 'Forks', 'Pad_Type', 'Ride_Control',
       'Stick', 'Transmission', 'Turbocharged', 'Blade_Extension',
       'Blade_Width', 'Enclosure_Type', 'Engine_Horsepower', 'Hydraulics',
       'Pushblock', 'Ripper', 'Scarifier', 'Tip_Control', 'Tire_Size',
       'Coupler', 'Coupler_System', 'Grouser_Tracks', 'Hydraulics_Flow',
       'Track_Type', 'Undercarriage_Pad_Width', 'Stick_Length', 'Thumb',
       'Pattern_Changer', 'Grouser_Type', 'Backhoe_Mounting', 'Blade_Type',
       'Travel_Controls', 'Differential_Type', 'Steering_Controls'],
      dtype='object')

In [116]:
#to categorize 'UsageBand' Column.
data[['UsageBand_High','UsageBand_Low','UsageBand_Medium']] = pd.get_dummies(data.UsageBand)
# data[['UsageBand_High','UsageBand_Low','UsageBand_Medium']] = pd.get_dummies(data.UsageBand, columns=['UsageBand_High','UsageBand_Low','UsageBand_Medium'])
data.pop('UsageBand')
data

SalesID  SalePrice  MachineID  ModelID  datasource  auctioneerID  \
0       1139246      66000     999089     3157         121           3.0   
1       1139248      57000     117657       77         121           3.0   
2       1139249      10000     434808     7009         121           3.0   
3       1139251      38500    1026470      332         121           3.0   
4       1139253      11000    1057373    17311         121           3.0   
5       1139255      26500    1001274     4605         121           3.0   
6       1139256      21000     772701     1937         121           3.0   
7       1139261      27000     902002     3539         121           3.0   
8       1139272      21500    1036251    36003         121           3.0   
9       1139275      65000    1016474     3883         121           3.0   
10      1139278      24000    1024998     4605         121           3.0   
11      1139282      22500     319906     5255         121           3.0   
12      1139283      36000    1052214     2232         121           3.0   
13      1139284      30500    1068082     3542         121           3.0   
14      1139290      28000    1058450     5162         121           3.0   
15      1139291      19000    1004810     4604         121           3.0   
16      1139292      13500    1026973     9510         121           3.0   
17      1139299       9500    1002713    21442         121           3.0   
18      1139301      12500     125790     7040         121           3.0   
19      1139304      11500    1011914     3177         121           3.0   
20      1139311      41000    1014135     8867         121           3.0   
21      1139333      34500     999192     3350         121           3.0   
22      1139344      26000    1044500     7040         121           3.0   
23      1139346      73000     821452       85         121           3.0   
24      1139348      33000     294562     3542         121           3.0   
25      1139351      12500     833838     7009         121           3.0   
26      1139354      15500     565440     7040         121           3.0   
27      1139356      53000    1004127    25458         121           3.0   
28      1139357      46000      44800    19167         121           3.0   
29      1139358      89000    1018076     1333         121           3.0   
...         ...        ...        ...      ...         ...           ...   
401095  6333259      10500    1872639    21437         149           1.0   
401096  6333260      10000    1816341    21437         149           2.0   
401097  6333261       8500    1843949    21437         149           1.0   
401098  6333262      10500    1791341    21437         149           2.0   
401099  6333263      11000    1833174    21437         149           1.0   
401100  6333264      10500    1791370    21437         149           2.0   
401101  6333270      10000    1799208    21437         149           1.0   
401102  6333272      10500    1927142    21437         149           2.0   
401103  6333273      12500    1789856    21437         149           2.0   
401104  6333275      10500    1924623    21437         149           2.0   
401105  6333276      10000    1835350    21437         149           2.0   
401106  6333278      10500    1944702    21437         149           2.0   
401107  6333279      12500    1866563    21437         149           2.0   
401108  6333280      10500    1851633    21437         149           2.0   
401109  6333281      10500    1798958    21437         149           2.0   
401110  6333282      10500    1878866    21437         149           2.0   
401111  6333283      10000    1874235    21437         149           2.0   
401112  6333284      10500    1887654    21437         149           2.0   
401113  6333285      10500    1817165    21437         149           2.0   
401114  6333287      12500    1918242    21437         149           2.0   
401115  6333290      10000    1843374    21437         1

In [117]:
# to categorize 'Thumb' column.
data[['Thumb_Hydraulic','Thumb_Manual','Thumb_None']] = pd.get_dummies(data.Thumb)
data.pop('Thumb')
data

SalesID  SalePrice  MachineID  ModelID  datasource  auctioneerID  \
0       1139246      66000     999089     3157         121           3.0   
1       1139248      57000     117657       77         121           3.0   
2       1139249      10000     434808     7009         121           3.0   
3       1139251      38500    1026470      332         121           3.0   
4       1139253      11000    1057373    17311         121           3.0   
5       1139255      26500    1001274     4605         121           3.0   
6       1139256      21000     772701     1937         121           3.0   
7       1139261      27000     902002     3539         121           3.0   
8       1139272      21500    1036251    36003         121           3.0   
9       1139275      65000    1016474     3883         121           3.0   
10      1139278      24000    1024998     4605         121           3.0   
11      1139282      22500     319906     5255         121           3.0   
12      1139283      36000    1052214     2232         121           3.0   
13      1139284      30500    1068082     3542         121           3.0   
14      1139290      28000    1058450     5162         121           3.0   
15      1139291      19000    1004810     4604         121           3.0   
16      1139292      13500    1026973     9510         121           3.0   
17      1139299       9500    1002713    21442         121           3.0   
18      1139301      12500     125790     7040         121           3.0   
19      1139304      11500    1011914     3177         121           3.0   
20      1139311      41000    1014135     8867         121           3.0   
21      1139333      34500     999192     3350         121           3.0   
22      1139344      26000    1044500     7040         121           3.0   
23      1139346      73000     821452       85         121           3.0   
24      1139348      33000     294562     3542         121           3.0   
25      1139351      12500     833838     7009         121           3.0   
26      1139354      15500     565440     7040         121           3.0   
27      1139356      53000    1004127    25458         121           3.0   
28      1139357      46000      44800    19167         121           3.0   
29      1139358      89000    1018076     1333         121           3.0   
...         ...        ...        ...      ...         ...           ...   
401095  6333259      10500    1872639    21437         149           1.0   
401096  6333260      10000    1816341    21437         149           2.0   
401097  6333261       8500    1843949    21437         149           1.0   
401098  6333262      10500    1791341    21437         149           2.0   
401099  6333263      11000    1833174    21437         149           1.0   
401100  6333264      10500    1791370    21437         149           2.0   
401101  6333270      10000    1799208    21437         149           1.0   
401102  6333272      10500    1927142    21437         149           2.0   
401103  6333273      12500    1789856    21437         149           2.0   
401104  6333275      10500    1924623    21437         149           2.0   
401105  6333276      10000    1835350    21437         149           2.0   
401106  6333278      10500    1944702    21437         149           2.0   
401107  6333279      12500    1866563    21437         149           2.0   
401108  6333280      10500    1851633    21437         149           2.0   
401109  6333281      10500    1798958    21437         149           2.0   
401110  6333282      10500    1878866    21437         149           2.0   
401111  6333283      10000    1874235    21437         149           2.0   
401112  6333284      10500    1887654    21437         149           2.0   
401113  6333285      10500    1817165    21437         149           2.0   
401114  6333287      12500    1918242    21437         149           2.0   
401115  6333290      10000    1843374    21437         1

In [118]:
# pd.get_dummies(data.UsageBand) #One hot encoding to remove categorial data when you have less variation in the feature.

In [49]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = array(data)
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)



['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


cold  hot  warm
0     1    0     0
1     1    0     0
2     0    0     1
3     1    0     0
4     0    1     0
5     0    1     0
6     0    0     1
7     1    0     0
8     0    0     1
9     0    1     0

In [5]:
m = RandomForestRegressor(n_jobs=-1)
m.fit(data.drop('SalePrice', axis=1), data.SalePrice)

ValueError: could not convert string to float: 'Conventional'